app = "pcg"
build = { }
primary_region = "sjc"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 4_000
min_machines_running = 0
processes = [ "app" ]

[[mounts]]
source = "pcg_vis_data"
destination = "/data"
initial_size = "10gb"

[[vm]]
cpu_kind = "performance"
cpus = 1
memory = "8gb"
